version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
      - "../:/var/www/html:rw"
      - "./web/php.ini:/usr/local/etc/php/php.ini:rw"
      - "./oracle/tnsnames.ora:/usr/lib/instantclient_21_13/network/admin/tnsnames.ora:ro"
    environment:
      - "TZ=Asia/Seoul"
    ports:
      - "8180:80"
    networks:
      - make-markdowns-from-database-tables-proxy
networks:
  make-markdowns-from-database-tables-proxy:
    driver: bridge
